---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: {{ .Release.Namespace }}

{{- if not (lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" .Values.ClusterRolename) }}
---
# ClusterRoleBinding for RBAC, only deployed once in the
# cluster, it will skip if it already exists

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ .Values.ClusterRolename }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: {{ .Release.Namespace }}
{{- end }}
