---
# Service for Vault Server
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
spec:
  type: NodePort  
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: {{ .Values.vaultPort }}
      targetPort: {{ .Values.vaultPort }}
      nodePort: {{ .Values.nodePort }}
    - name: https-internal
      port: {{ .Values.vaultInternalPort }}
      targetPort: {{ .Values.vaultInternalPort }}
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server

---
# Headless Service
apiVersion: v1
kind: Service
metadata:
  name: vault-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  annotations:
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: {{ .Values.vaultPort }}
      targetPort: {{ .Values.vaultPort }}
    - name: https-internal
      port: {{ .Values.vaultInternalPort }}
      targetPort: {{ .Values.vaultInternalPort }}
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    component: server
